version: '3.7'

services:

  apartment-manager-ui:
    container_name: apartment-manager-ui
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '4201:4200'